Assignment 8-Docker/mysite/main/urls.py
from django.urls import path
from . import views

app_name = "main"   

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:sorted>/", views.homepage, name="homepage"),
    path("edit/<int:id>/",views.update, name="update"),
    path("destroy/<int:id>/", views.destroy, name="destroy"),
    path("show/<int:id>/", views.show, name="show"),
    path("search/", views.search, name="search"),
    path("show_all/<slug:profession>", views.show_all, name="show_all"),
    path("compare_names/", views.compare_names, name="compare_names")
]

Assignment 8-Docker/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

Assignment 8-Docker/mysite/main/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=100)
    profession = models.CharField(max_length=100)
    telephone1 = models.CharField(max_length=100)
    telephone2 = models.CharField(max_length=100)

Assignment 8-Docker/mysite/main/forms.py
from django import forms
from .models import Person

class PersonForm(forms.ModelForm):
  class Meta:
    model = Person
    fields = ('id','name','profession','telephone1','telephone2')

Assignment 8-Docker/mysite/main/views.py
from django.shortcuts import render, redirect
from .forms import PersonForm
from .models import Person

# Create your views here.
def index(request):
  return redirect("/0/")

def compare_names(request):
  if request.method == "POST":
    name1 = request.POST['name1']
    name2 = request.POST['name2']
    person1 = Person.objects.get(name = name1)
    person2 = Person.objects.get(name = name2)
    if person1.profession == person2.profession and person1.telephone1 == person2.telephone1 and person1.telephone2 == person2.telephone2:
      return redirect("/3/")
    else:
      return redirect("/4/")

def homepage(request, sorted = 0):
  if sorted == 1:
    persons = Person.objects.order_by("name")
  elif sorted == 2:
    persons = Person.objects.order_by("profession")
  else:
    persons = Person.objects.all()
  if sorted == 3:
    compare_status = 2
  elif sorted == 4:
    compare_status = 1
  else:
    compare_status = 0
  if request.method == "POST":
    form = PersonForm(request.POST)
    if form.is_valid():
      form.save()
  form = PersonForm()
  return render(request, "home.html", {"form": form, "persons":persons, "compare_status": compare_status})

def show(request, id):
  if id == 0:
    return render(request, 'show.html', {'error': True})
  person = Person.objects.get(id=id)
  return render(request, 'show.html', {'person':person})

def show_all(request, profession):
  persons = Person.objects.filter(profession = profession)
  if len(persons) > 0:
    return render(request, 'show.html', {'persons':persons})
  else:
    return render(request, 'show.html', {'error': True})
    

def search(request):
  try:
    print(request.POST)
    if request.POST['name'] != "":
      person = Person.objects.get(name = request.POST['name'])
    elif request.POST['telephone1']:
      person = Person.objects.get(telephone1 = request.POST['telephone1'])
    elif request.POST['profession']:
      return redirect("/show_all/{}".format(request.POST['profession']))
    elif request.POST['telephone2']:
      person = Person.objects.get(telephone2 = request.POST['telephone2'])
  except Exception as e:
    person = Person(id=0)
  return redirect("/show/{}".format(person.id))


def destroy(request, id):
  person = Person.objects.get(id=id)
  person.delete()
  return redirect('/')
def update(request,id):  
  person = Person.objects.get(id= id)
  form = PersonForm(request.POST, instance = person)
  if form.is_valid():
    form.save()
    return redirect('/')
  return render(request, 'edit.html', {"form": form, 'person':person})

Assignment 8-Docker/mysite/main/templates/edit.html
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>
    {% load crispy_forms_tags %}

    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand mx-auto" href="/">
            Home
        </a>

    </nav>
    <br><br>

    <div class="container">
        <form method="POST" class="post-form" action="/edit/{{person.id}}/">
            {% csrf_token %}
            <div class="container">
                <br>
                <div id="div_id_name" class="form-group"> <label for="id_name" class=" requiredField">
                        Name<span class="asteriskField">*</span> </label>
                    <div> <input type="text" name="name" maxlength="100" class="textinput textInput form-control"
                            required id="id_name" value="{{person.name}}"> </div>
                </div>
                <div id="div_id_profession" class="form-group"> <label for="id_profession" class=" requiredField">
                        Profession<span class="asteriskField">*</span> </label>
                    <div> <input type="text" name="profession" maxlength="100" class="textinput textInput form-control"
                            required id="id_profession" value="{{person.profession}}"> </div>
                </div>
                <div id="div_id_telephone1" class="form-group"> <label for="id_telephone1" class=" requiredField">
                        Telephone1<span class="asteriskField">*</span> </label>
                    <div> <input type="text" name="telephone1" maxlength="100" class="textinput textInput form-control"
                            required id="id_telephone1" value="{{person.telephone1}}"> </div>
                </div>
                <div id="div_id_telephone2" class="form-group"> <label for="id_telephone2" class=" requiredField">
                        Telephone2<span class="asteriskField">*</span> </label>
                    <div> <input type="text" name="telephone2" maxlength="100" class="textinput textInput form-control"
                            required id="id_telephone2" value="{{person.telephone2}}"> </div>
                </div>

                <br>
                <button class="btn btn-primary" type="submit" id="submit_button">Submit</button>
            </div>
    </div>
    </div>
    </form>
    </div>
    <br><br>

</body>

</html>

Assignment 8-Docker/mysite/main/templates/home.html
<!DOCTYPE html>
<html>

<head>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!--Bootstrap CSS-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
  {% load crispy_forms_tags %}

  <nav class="navbar fixed-top navbar-light bg-light navbar-expand">
    <a class="navbar-brand mr-3" href="/">
      Person Database
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <!-- <li class="nav-item active">
          <a class="nav-link" href="#searchContainer">Search </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#sortContainer">Sort</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#compareContainer">Compare</a>
        </li> -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Tools
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#searchContainer">Search </a>
            <a class="dropdown-item" href="#sortContainer">Sort</a>
            <a class="dropdown-item" href="#compareContainer">Compare</a>
            <a class="dropdown-item" href="#viewContainer">View All</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
  <br><br>
  <br><br>

  <div class="container">
    <form method="post">
      Create New Person
      <br/>
      <br/>
      {% csrf_token %}
      {{ form|crispy }}
      <br>
      <button class="btn btn-primary" type="submit" id="submit_button">Submit</button>
    </form>
  </div>
  <br id="searchContainer"><br>
  <hr />
  <br><br>

  <div class="container" style="width:25%;">
    <form method="post" action="/search/">
      {% csrf_token %}
      <div id="div_id_name" class="form-group"> <label for="id_name" class=" requiredField">
          Search for person using Name </label>
        <div> <input type="text" name="name" maxlength="100" class="textinput textInput form-control" id="id_name">
        </div>
      </div>
      <div id="div_id_telephone1" class="form-group"> <label for="id_telephone1" class=" requiredField">
          Search for person using Telephone 1 </label>
        <div> <input type="text" name="telephone1" maxlength="100" class="textinput textInput form-control"
            id="id_telephone1"> </div>
      </div>
      <div id="div_id_telephone2" class="form-group"> <label for="id_telephone2" class=" requiredField">
          Search for person using Telephone 2 </label>
        <div> <input type="text" name="telephone2" maxlength="100" class="textinput textInput form-control"
            id="id_telephone2"> </div>
      </div>
      <div id="div_id_profession" class="form-group"> <label for="id_profession" class=" requiredField">
          Search for person using Profession </label>
        <div> <input type="text" name="profession" maxlength="100" class="textinput textInput form-control"
            id="id_profession"> </div>
      </div>
      <br>
      <button class="btn btn-primary" type="submit" id="submit_button">Submit</button>
    </form>

  </div>
  <br id="sortContainer"><br>

  <hr />

  <div class="container">
    <a class="btn btn-primary" href="/1/"> Sort by name </a>
    <a class="btn btn-success" href="/2/"> Sort by profession </a>
    <br id="compareContainer" />
    <br />
    <br />

    <form method="post" action="/compare_names/">
      {% csrf_token %}
      Compare Two People
      <br />
      <br />

      <div id="div_id_name" class="form-group"> <label for="id_name1" class=" requiredField">
          First Name </label>
        <div> <input type="text" name="name1" maxlength="100" class="textinput textInput form-control" id="id_name1">
        </div>
        <div id="div_id_name" class="form-group"> <label for="id_name2" class=" requiredField">
            Second Name </label>
          <div> <input type="text" name="name2" maxlength="100" class="textinput textInput form-control" id="id_name2">
          </div>
        </div>
        <button class="btn btn-primary" type="submit" id="submit_button">Submit</button>
    </form>
    <br/>
    <br/>
    {% if compare_status == 2 %}
    <a> True, The two names have the same profession and telephone numbers</a>
    {% endif %}
    {% if compare_status == 1 %}
    <a> False, the two names do not have the same attributes </a>
    {% endif %}
    <br id="viewContainer"/>

    <br/>
    <br/>

    {% for person in persons %}
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">{{ person.name }}</h5>
        <p class="card-text">Profession: {{ person.profession }}</p>
        <p class="card-text">Telephone1: {{ person.telephone1 }}</p>
        <p class="card-text">Telephone2: {{ person.telephone2 }}</p>
        <a class="btn btn-danger" href="/destroy/{{person.id}}"> Destroy </a>
        <a class="btn btn-primary" href="/edit/{{person.id}}"> Update </a>

      </div>
    </div>
    {% endfor %}
  </div>

</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

Assignment 8-Docker/mysite/main/templates/show.html
<!DOCTYPE html>
<html>

<head>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!--Bootstrap CSS-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>
  {% load crispy_forms_tags %}

  <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand mx-auto" href="/">
      Home
    </a>
  </nav>
  <br><br>
  <div class="container" style="width:25%;">
    <form method="post" action="/search/">
      {% csrf_token %}
      <div id="div_id_name" class="form-group"> <label for="id_name" class=" requiredField">
          Search for person using Name </label>
        <div> <input type="text" name="name" maxlength="100" class="textinput textInput form-control"
            id="id_name"> </div>
      </div>
      <div id="div_id_telephone1" class="form-group"> <label for="id_telephone1" class=" requiredField">
          Search for person using Telephone 1 </label>
        <div> <input type="text" name="telephone1" maxlength="100" class="textinput textInput form-control"
            id="id_telephone1"> </div>
      </div>
      <div id="div_id_telephone2" class="form-group"> <label for="id_telephone2" class=" requiredField">
        Search for person using Telephone 2 </label>
      <div> <input type="text" name="telephone2" maxlength="100" class="textinput textInput form-control"
          id="id_telephone2"> </div>
    </div>
    <div id="div_id_profession" class="form-group"> <label for="id_profession" class=" requiredField">
      Search for person using Profession </label>
    <div> <input type="text" name="profession" maxlength="100" class="textinput textInput form-control"
        id="id_profession"> </div>
    </div>
        <br>
      <br>
      <button class="btn btn-primary" type="submit" id="submit_button">Submit</button>
    </form>
  </div>
  <div class="container">
    
    {% if not error%}
        {% if not persons %}
        <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ person.name }}</h5>
            <p class="card-text">Profession: {{ person.profession }}</p>
            <p class="card-text">Telephone1: {{ person.telephone1 }}</p>
            <p class="card-text">Telephone2: {{ person.telephone2 }}</p>
            <a class="btn btn-danger" href="/destroy/{{person.id}}"> Destroy </a>
            <a class="btn btn-primary" href="/edit/{{person.id}}"> Update </a>
        </div>
        
        </div>
        {% else %}
        {% for person in persons %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ person.name }}</h5>
                <p class="card-text">Profession: {{ person.profession }}</p>
                <p class="card-text">Telephone1: {{ person.telephone1 }}</p>
                <p class="card-text">Telephone2: {{ person.telephone2 }}</p>
                <a class="btn btn-danger" href="/destroy/{{person.id}}"> Destroy </a>
                <a class="btn btn-primary" href="/edit/{{person.id}}"> Update </a>
            </div>
        {% endfor %}
        {% endif %}
    {% else %}
    <p> No people found with this search or multiple people</p>
    {% endif %}

  </div>
  
  <br><br>

  <hr/>
  
</body>

</html>